### ISSUE TITLE
Tests fail with 'listen EADDRINUSE' and 'Timeout of 3000ms exceeded'.

### ISSUE THREAD

**Issue by mgaggero** [telefonicaid/iotagent-ul#363]
**Description**
Hi,
running the test suite for iotagent-ul on the master branch of official repository it gives me several errors of types 'listen EADDRINUSE' and 'Timeout of 3000ms exceeded'.

Is anything missing in my environment or the test suite is broken?
A properly working test suite is needed to me in order to create a patch to address #361.

**How to reproduce**:
```
git clone https://github.com/telefonicaid/iotagent-ul.git

cd iotagent-ul
npm install
npm test
```

**Output**
```
> iotagent-ul@1.9.0-next test /private/tmp/iotagent-ul
> mocha --recursive 'test/**/*.js' --reporter spec --timeout 3000 --ui bdd --exit



  AMQP Transport binding: measures
(node:2401) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.
    When a new single measure arrives to a Device routing key
      1) "before each" hook for "should send a new update context request to the Context Broker with just that attribute"
      2) "after each" hook for "should send a new update context request to the Context Broker with just that attribute"

  Data Bidirectionality: HTTP
    When a bidirectional attribute is set and a new value arrives to a device without endpoint
      3) "before each" hook for "should return a 200 OK"
    When a bidirectional attribute is set and a new value arrives to a device with endpoint
      4) "before each" hook
time=2019-06-21T10:11:42.311Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:11:42.311Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
      5) "after each" hook for "should return a 200 OK"

  AMQP Transport binding: commands
    When a command arrive to the Agent for a device with the AMQP protocol
      6) "before each" hook for "should return a 200 OK without errors"
      7) "after each" hook for "should return a 200 OK without errors"

  HTTP Transport binding: commands
    When a command arrive to the Agent for a device with the HTTP_UL protocol
      8) "before each" hook
time=2019-06-21T10:11:48.329Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:11:48.329Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:11:48.329Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:11:48.329Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
      9) "after each" hook for "should return a 200 OK without errors"

  MQTT Transport binding: commands
    When a command arrive to the Agent for a device with the MQTT_UL protocol
      10) "before each" hook for "should return a 200 OK without errors"
      11) "after each" hook for "should return a 200 OK without errors"

  HTTP Transport binding: polling commands
    When a command arrives to the IoTA with HTTP transport and no endpoint
      12) "before each" hook
time=2019-06-21T10:11:57.348Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:11:57.348Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:11:57.348Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:11:57.348Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:11:57.348Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:11:57.348Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
      13) "after each" hook for "should return a 200 OK without errors"

  HTTP Transport binding: measures
    When a new single measure arrives for a Device, via HTTP GET
      14) "before each" hook for "should end up with a 200OK status code"
      15) "after each" hook for "should end up with a 200OK status code"

  MQTT Transport binding: measures
    When a new single measure arrives to a Device topic
      16) "before each" hook
time=2019-06-21T10:12:06.362Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:12:06.362Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:12:06.362Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:12:06.362Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:12:06.362Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:12:06.362Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:12:06.362Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:12:06.362Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
      17) "after each" hook for "should send a new update context request to the Context Broker with just that attribute"

  AMQP Transport binding: measures
    When a new single measure arrives to a Device routing key
(node:2401) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added. Use emitter.setMaxListeners() to increase limit
      18) "before each" hook for "should send a new update context request to the Context Broker with just that attribute"
      19) "after each" hook for "should send a new update context request to the Context Broker with just that attribute"

  Data Bidirectionality: HTTP
    When a bidirectional attribute is set and a new value arrives to a device without endpoint
      20) "before each" hook
time=2019-06-21T10:12:12.378Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:12:12.378Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:12:12.378Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:12:12.378Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:12:12.379Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:12:12.379Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:12:12.379Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:12:12.379Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:12:12.379Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:12:12.379Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
      21) "after each" hook for "should return a 200 OK"

  HTTP Transport binding: measures
    When a new single measure arrives for a Device, via HTTP GET
      22) "before each" hook for "should end up with a 200OK status code"
      23) "after each" hook for "should end up with a 200OK status code"

  MQTT Transport binding: measures
    When a new single measure arrives to a Device topic
      24) "before each" hook
time=2019-06-21T10:12:21.398Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:12:21.398Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:12:21.398Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:12:21.398Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:12:21.398Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:12:21.398Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:12:21.399Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:12:21.399Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:12:21.399Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:12:21.399Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:12:21.399Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
time=2019-06-21T10:12:21.399Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: listen EADDRINUSE: address already in use 0.0.0.0:4061 | comp=IoTAgent
      25) "after each" hook for "should send a new update context request to the Context Broker with just that attribute"

  Startup tests
    When the IoT Agent is started with environment variables
      26) should load the environment variables in the internal configuration
      27) "after each" hook for "should load the environment variables in the internal configuration"

  Ultralight 2.0 Parser: measures
    When a payload with a single measure is parsed
      ✓ should return an array with a single object with just one attribute
    When a payload with a multiple measures is parsed
      ✓ should return an array with a single object with multiple attributes
    When a payload with timestamp information is parsed
      ✓ should add a TimeInstant attribute to the array with the value
    When a payload with an initial bar and multiple measures is parsed
      ✓ should return an array with a single object with multiple attributes
    When a payload with two groups of measures and one measure in each group is parsed
      ✓ should return an array with two objects with just one attribute
    When a payload with multiple groups and measures is parsed
      ✓ should return an array with the parsed groups and objects
    When a payload with command results is parsed
      ✓ should return an array with the parsed groups and the command
    When a payload with an empty measure is found: "a|10||"
      ✓ should throw a PARSE_ERROR error
    When a payload with an empty measure group is found: "a|10|b|11##t|3"
      ✓ should throw a PARSE_ERROR error
    When an empty payload is parsed
      ✓ should throw a PARSE_ERROR error

  Ultralight 2.0 Parser: commands
    When a command execution with multiple parameters is parsed
      ✓ should extract the deviceId, the command name, and the parameters
    When a command execution with no params and a value is parsed
      ✓ should extract the deviceId, the command name, and the plain text of the value
    When a command result is parsed
      should extract the deviceId, the command name, and the result
        ✓ should extract the deviceId, the command name, and the parameters


  13 passing (54s)
  27 failing

  1) AMQP Transport binding: measures
       "before each" hook for "should send a new update context request to the Context Broker with just that attribute":
     Error: Timeout of 3000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/private/tmp/iotagent-ul/test/unit/amqpBinding-test.js)
  

  2) AMQP Transport binding: measures
       "after each" hook for "should send a new update context request to the Context Broker with just that attribute":
     TypeError: Cannot read property 'close' of undefined
      at Context.<anonymous> (test/unit/amqpBinding-test.js:89:18)
      at process.topLevelDomainCallback (domain.js:126:23)

  3) Data Bidirectionality: HTTP
       When a bidirectional attribute is set and a new value arrives to a device without endpoint
         "before each" hook for "should return a 200 OK":
     Error: Timeout of 3000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/private/tmp/iotagent-ul/test/unit/bidirectionalityHttp-test.js)
  

  4) Data Bidirectionality: HTTP
       When a bidirectional attribute is set and a new value arrives to a device with endpoint
         "before each" hook:
     Uncaught Error: listen EADDRINUSE: address already in use 0.0.0.0:4061
      at Server.setupListenHandle [as _listen2] (net.js:1256:14)
      at listenInCluster (net.js:1304:12)
      at doListen (net.js:1443:7)
      at processTicksAndRejections (internal/process/next_tick.js:76:17)

  5) Data Bidirectionality: HTTP
       "after each" hook for "should return a 200 OK":
     Error: Timeout of 3000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/private/tmp/iotagent-ul/test/unit/bidirectionalityHttp-test.js)
  

  6) AMQP Transport binding: commands
       "before each" hook for "should return a 200 OK without errors":
     Error: Timeout of 3000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/private/tmp/iotagent-ul/test/unit/commandsAmqp-test.js)
  

  7) AMQP Transport binding: commands
       "after each" hook for "should return a 200 OK without errors":
     TypeError: Cannot read property 'close' of undefined
      at Context.<anonymous> (test/unit/commandsAmqp-test.js:102:18)
      at process.topLevelDomainCallback (domain.js:126:23)

  8) HTTP Transport binding: commands
       "before each" hook:
     Uncaught Error: listen EADDRINUSE: address already in use 0.0.0.0:4061
      at Server.setupListenHandle [as _listen2] (net.js:1256:14)
      at listenInCluster (net.js:1304:12)
      at doListen (net.js:1443:7)
      at processTicksAndRejections (internal/process/next_tick.js:76:17)

  9) HTTP Transport binding: commands
       "after each" hook for "should return a 200 OK without errors":
     Error: Timeout of 3000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/private/tmp/iotagent-ul/test/unit/commandsHttp-test.js)
  

  10) MQTT Transport binding: commands
       "before each" hook for "should return a 200 OK without errors":
     Error: Timeout of 3000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/private/tmp/iotagent-ul/test/unit/commandsMqtt-test.js)
  

  11) MQTT Transport binding: commands
       "after each" hook for "should return a 200 OK without errors":
     Error: Timeout of 3000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/private/tmp/iotagent-ul/test/unit/commandsMqtt-test.js)
  

  12) HTTP Transport binding: polling commands
       "before each" hook:
     Uncaught Error: listen EADDRINUSE: address already in use 0.0.0.0:4061
      at Server.setupListenHandle [as _listen2] (net.js:1256:14)
      at listenInCluster (net.js:1304:12)
      at doListen (net.js:1443:7)
      at processTicksAndRejections (internal/process/next_tick.js:76:17)

  13) HTTP Transport binding: polling commands
       "after each" hook for "should return a 200 OK without errors":
     Error: Timeout of 3000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/private/tmp/iotagent-ul/test/unit/commandsPolling-test.js)
  

  14) HTTP Transport binding: measures
       "before each" hook for "should end up with a 200OK status code":
     Error: Timeout of 3000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/private/tmp/iotagent-ul/test/unit/httpBinding-test.js)
  

  15) HTTP Transport binding: measures
       "after each" hook for "should end up with a 200OK status code":
     Error: Timeout of 3000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/private/tmp/iotagent-ul/test/unit/httpBinding-test.js)
  

  16) MQTT Transport binding: measures
       "before each" hook:
     Uncaught Error: listen EADDRINUSE: address already in use 0.0.0.0:4061
      at Server.setupListenHandle [as _listen2] (net.js:1256:14)
      at listenInCluster (net.js:1304:12)
      at doListen (net.js:1443:7)
      at processTicksAndRejections (internal/process/next_tick.js:76:17)

  17) MQTT Transport binding: measures
       "after each" hook for "should send a new update context request to the Context Broker with just that attribute":
     Error: Timeout of 3000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/private/tmp/iotagent-ul/test/unit/mqttBinding-test.js)
  

  18) AMQP Transport binding: measures
       "before each" hook for "should send a new update context request to the Context Broker with just that attribute":
     Error: Timeout of 3000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/private/tmp/iotagent-ul/test/unit/ngsiv2/amqpBinding-test.js)
  

  19) AMQP Transport binding: measures
       "after each" hook for "should send a new update context request to the Context Broker with just that attribute":
     TypeError: Cannot read property 'close' of undefined
      at Context.<anonymous> (test/unit/ngsiv2/amqpBinding-test.js:94:18)
      at process.topLevelDomainCallback (domain.js:126:23)

  20) Data Bidirectionality: HTTP
       When a bidirectional attribute is set and a new value arrives to a device without endpoint
         "before each" hook:
     Uncaught Error: listen EADDRINUSE: address already in use 0.0.0.0:4061
      at Server.setupListenHandle [as _listen2] (net.js:1256:14)
      at listenInCluster (net.js:1304:12)
      at doListen (net.js:1443:7)
      at processTicksAndRejections (internal/process/next_tick.js:76:17)

  21) Data Bidirectionality: HTTP
       "after each" hook for "should return a 200 OK":
     Error: Timeout of 3000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/private/tmp/iotagent-ul/test/unit/ngsiv2/bidirectionalityHttp-test.js)
  

  22) HTTP Transport binding: measures
       "before each" hook for "should end up with a 200OK status code":
     Error: Timeout of 3000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/private/tmp/iotagent-ul/test/unit/ngsiv2/httpBindings-test.js)
  

  23) HTTP Transport binding: measures
       "after each" hook for "should end up with a 200OK status code":
     Error: Timeout of 3000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/private/tmp/iotagent-ul/test/unit/ngsiv2/httpBindings-test.js)
  

  24) MQTT Transport binding: measures
       "before each" hook:
     Uncaught Error: listen EADDRINUSE: address already in use 0.0.0.0:4061
      at Server.setupListenHandle [as _listen2] (net.js:1256:14)
      at listenInCluster (net.js:1304:12)
      at doListen (net.js:1443:7)
      at processTicksAndRejections (internal/process/next_tick.js:76:17)

  25) MQTT Transport binding: measures
       "after each" hook for "should send a new update context request to the Context Broker with just that attribute":
     Error: Timeout of 3000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/private/tmp/iotagent-ul/test/unit/ngsiv2/mqttBinding-test.js)
  

  26) Startup tests
       When the IoT Agent is started with environment variables
         should load the environment variables in the internal configuration:
     Error: Timeout of 3000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/private/tmp/iotagent-ul/test/unit/startup-test.js)
  

  27) Startup tests
       When the IoT Agent is started with environment variables
         "after each" hook for "should load the environment variables in the internal configuration":
     Error: Timeout of 3000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/private/tmp/iotagent-ul/test/unit/startup-test.js)
  



npm ERR! Test failed.  See above for more details.
```

**Results expected**
All test passing

Thanks,
  Massimo.

**Comment by fgalan** [comment]
Looking to what travis does to run the tests (https://github.com/telefonicaid/iotagent-ul/blob/master/.travis.yml#L22) maybe you need to install the mosquitto docker

      before_install:
        - docker pull ansi/mosquitto
        - docker run -d -p 1883:1883 -l mosquitto ansi/mosquitto

(In general it's a good idea to use .travis.yml as reference. It contains the "script" to run the tests that travis uses)

Note that even in that case there is a test that uses to "glitch" so maybe you will get something like this:

```
129 passing (18s)
  3 pending
  1 failing
  1) AMQP Transport binding: commands
       When a command arrive to the Agent for a device with the AMQP protocol
         should publish the command information in the AMQP topic:
     Error: Timeout of 3000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/travis/build/telefonicaid/iotagent-ul/test/unit/commandsAmqp-test.js)
```

The solution is to re-run the test until it works.

In fact it would be great if somebody could have a look to that test and find out a way to stabilize it :)

**Comment by mgaggero** [comment]
Ok, thanks for the directions. I have managed to run the test suite successfully on a Ubuntu+Docker VM installing the containers for Mongo and RabbitMQ:

```
docker pull ansi/mosquitto
docker pull mongo
docker pull rabbitmq

docker run -d -p 1883:1883 -l mosquitto ansi/mosquitto
docker run -d -p 27017:27017 -l mongodb mongo
docker run -d -p 5672:5672 -l rabbitmq rabbitmq

npm install
npm run lint
npm test
```

**Comment by fgalan** [comment]
Great!

Should the issue be close?

**Comment by mgaggero** [comment]
Yes, thanks!
