### ISSUE TITLE
No compatibility with MOSQUITTO > 2.0 version

### ISSUE THREAD

**Issue by hbrito-gtc** [telefonicaid/iotagent-ul#527]
I'm trying to use MQTT and IoTAgent Ultralight with Docker. For this, I use IoTAgent UltraLight version 1.19.0, but with Mosquitto version 2.0, or higher, it fails. At the moment I'm using Mosquitto 2.0.14 version.

But if I change this Mosquitto for version 1.6.14, that's OK!

The IotAgentUL error log:

```
time=2022-01-04T21:37:55.031Z | lvl=FATAL | corr=n/a | trans=n/a | op=n/a | from=n/a | srv=n/a | subsrv=n/a | msg=GLOBAL-002: Couldn't connect with MQTT broker: {"code":2} | comp=IoTAgent
time=2022-01-04T21:37:55.032Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | from=n/a | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: Callback was already called.
    at /opt/iotaul/node_modules/async/dist/async.js:966:32
    at MqttClient.<anonymous> (/opt/iotaul/lib/bindings/MQTTBinding.js:329:17)
    at MqttClient.emit (events.js:314:20)
    at MqttClient.EventEmitter.emit (domain.js:483:12)
    at MqttClient._handleConnack (/opt/iotaul/node_modules/mqtt/lib/client.js:1078:10)
    at MqttClient._handlePacket (/opt/iotaul/node_modules/mqtt/lib/client.js:365:12)
    at work (/opt/iotaul/node_modules/mqtt/lib/client.js:283:12)
    at Writable.writable._write (/opt/iotaul/node_modules/mqtt/lib/client.js:294:5)
    at doWrite (/opt/iotaul/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/opt/iotaul/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/opt/iotaul/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Socket.ondata (_stream_readable.js:718:22)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:506:15)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at TCP.callbackTrampoline (internal/async_hooks.js:126:14) | comp=IoTAgent
time=2022-01-04T21:37:55.033Z | lvl=WARN | corr=n/a | trans=n/a | op=IOTAUL.MQTT.Binding | from=n/a | srv=n/a | subsrv=n/a | msg=reconnecting... | comp=IoTAgent
```

The error is constantly repeated. 

And yes, I putted in mosquitto.conf the configuration for mosquitto version upper than 2.0:
_allow_anonymous true
listener 1883_

A lot of thanks,

Henry

**Comment by hbrito-gtc** [comment]
I've been doing some research, and have found that in this issue [ISSUE 455](https://github.com/telefonicaid/iotagent-json/issues/455) it says that the parameter keepalive, if it is 0, can cause problems, and it default value is 0. 
I thought it was fixed reading the RELEASE NOTE:

```
1.16.0

Changes (since 1.15.0):

    Fix: Set 60 seconds for default mqtt keepalive option (#370)
```
But in the latest code (MQTTBinding.js):
```
        ...
        clientId: mqttConfig.clientId ? mqttConfig.clientId : 'iotaul_' + Math.random().toString(16).substr(2, 8),
        keepalive: mqttConfig.keepalive ? parseInt(mqttConfig.keepalive) : 0,
        ...
```
Is possible to fix this in the next release?
For the moment, the workaround is to add a value to keeplive greater than zero in the docker-compose, for example:
`- IOTA_MQTT_KEEPALIVE = 60`

Regards,

Henry

**Comment by AlvaroVega** [comment]
Thanks for your report @hbrito-gtc

**Comment by hbrito-gtc** [comment]
Thanks @AlvaroVega !!

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-ul/pull/528 (and twin PR in IOTA-JSON: https://github.com/telefonicaid/iotagent-json/pull/607)

@hbrito-gtc it would be great if you could check if your problem has been fixed now in the new versions in master
