### ISSUE TITLE
[bug] Iotagent dies after several invalid updates

### ISSUE THREAD

**Issue by XavierVal** [telefonicaid/iotagent-ul#53]
Sending the no UL message to the subscribed topic of the iotagent: 
```
  mosquitto_pub -d -h x.x.x.x -t /1234/devnnt1/attrs -u user -P xxx -m "hola"
```

It is curious because the first attempt shows that the exception it is properly treated but the second one makes it go down.
  
```
#first attempt
time=2016-05-09T16:25:06.334Z | lvl=DEBUG | corr=d75bd092-d75a-4f23-815d-e98066e85558 | trans=d75bd092-d75a-4f23-815d-e98066e85558 | op=IoTAgentNGSI.MongoDBDeviceRegister | srv=n/a | subsrv=n/a | msg=Looking for entity with id [devnnt1].
time=2016-05-09T16:25:06.346Z | lvl=ERROR | corr=d75bd092-d75a-4f23-815d-e98066e85558 | trans=d75bd092-d75a-4f23-815d-e98066e85558 | op=IOTAUL.MQTT.Binding | srv=tservi70111 | subsrv=/sub1 | msg=undefined | name=PARSE_ERROR | message=There was a syntax error in the Ultralight request: Parsing group:hola | code=400 | domain=[object Object] | domainThrown=true
time=2016-05-09T16:25:06.346Z | lvl=DEBUG | corr=d75bd092-d75a-4f23-815d-e98066e85558 | trans=d75bd092-d75a-4f23-815d-e98066e85558 | op=IOTAUL.MQTT.Binding | srv=tservi70111 | subsrv=/sub1 | msg=response-time: 70625
time=2016-05-09T16:35:10.970Z | lvl=DEBUG | corr=n/a | trans=n/a | op=IoTAgentNGSI.MongoDBDeviceRegister | srv=tservi70111 | subsrv=/sub1 | msg=Looking for entity with id [devnnt1].


#second attempt
events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Domain.emit (events.js:74:15)
    at process._fatalException (node.js:278:29)
```

**Comment by dmoranj** [comment]
Only reproducible in Node.js v0.10.42 and below (fixed in v0.10.44). Either way, the case where a syntax error appears is not well treated. We will use this opportunity to improve the error management.
